### ISSUE TITLE
city planner problems

### ISSUE THREAD

**Issue by AllanLJones** [mainIine/foe-helfer-extension#1152]
Windows10 64 bit
Chrome 83.0.4103.61
en
When I submit data to the planner the buildings dont line up with the expansions. They are all two tiles higher and leave two rows of tiles empty at the bottom,
Also empty expansion tiles do not show.

**Comment by StrDar** [comment]
Same Problem here. I Opened an old saved City and now all Buildings are two Rows in the Air at the Top.

**Comment by SpellfireCA** [comment]
Sam Problem with Firefox, Chrome and Edge

**Comment by dsiekiera** [comment]
Sure. All old cities have this tiny offset issue. 
Pls try, for a small test, a new city. Place some buildings, save. Leave it and reload it.
If it works, pls move the offset building in the original position and save it again.

**Comment by SpellfireCA** [comment]
Ok will try. Last week imported cities from the game worked fine, it just started to happen a couple f days ago that imported cities from the game where offset

**Comment by dsiekiera** [comment]
Yes. I fixed this issue 2 days ago. Pls take a look to the changelog of the cityplanner in the planners overview.

**Comment by StrDar** [comment]
Sorry but it is not fixed for me. Same Problem. I Imported my City today, same two Row Error. I can't move 200 Buildings per Hand!?

**Comment by Moonie-73** [comment]
Same issue here.

**Comment by zarax23** [comment]
Hab das gleiche Problem. Alle Gebäude um 2 nach oben versetzt. Da kann ich speichern und Laden aber immer das gleiche Resultat. 
Same here.

**Comment by dsiekiera** [comment]
I updated this tool a few minutes ago.
Sollte nun funktionieren.
