### ISSUE TITLE
[bug] Large delays when changing armies

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#2747]
Today I encountered a problem: when changing the army in the Guild Battlefields, the delay on each unit is up to 10 seconds. There is no delay in the city and on GvG. There is a delay in the guild expedition.

The delay does not occur in all browsers. There is a delay in Chromium and Maxthon browsers. There is no delay in Brave, Yandex and Vivaldi browsers. Other browsers not tested.

The delay is 100% caused by Helper. When the extension is disabled, there is no delay. When the extension is enabled, there is a delay.

The delay is somehow dependent on the FP bar. If the bar is empty, there is no delay. If the bar is filled with FP (more than 10, less than 100), there is a delay.

Latest Helper version - 3.6.1.0

**Comment by outoftheline** [comment]
Fixed, please update

**Comment by 666shutter** [comment]
It seams that this problem still persist.
Hleper version 3.6.5.0

**Comment by Beelzebob6666** [comment]
please be aware that if you use stacked units there is an inherent lag when you have huge amounts of units in your army - this is a game issue not a helper issue.

if the lag issue goes away when you disable the helper, please report in more detail what you are doing and what and when the lag happens, as there is no apparent lag on my end.
