### ISSUE TITLE
Treasury Log Export: incorrect dates for dates earlier than the relative (pseudo-) dates

### ISSUE THREAD

**Issue by kleopatra** [mainIine/foe-helfer-extension#3164]
we started a discussion on [discord](https://discord.com/channels/577475401144598539/1311685279945326663/1322162000985456672) but as the improvement now is part of the release notes, it might be time for a real bug report :)

Problem is the date/time field of the treasury log: it's a pseudo/relative date (like "yesterday at 7:00 pm", or "on Thursday at 11:00 am") for the last six/seven days, and more like a "real" date (like "on 1/15/25 at 11:59") for older entries. The entries are localized, the example is for beta.

<img width="149" alt="Image" src="https://github.com/user-attachments/assets/5d5be257-df51-4062-8805-9346ffa0b01b" />

The conversion of the pseudo date/time entries are working fine, but the older dates are incorrect, note 

- the jump forward in date from 16 -> 19, it should be 16 -> 15
- the incorrect time part (which might be a different issue, am/pm -> military time seems to be wrong on other dates as well, just saw it but didn't dig)

16.1.2025 12:00:00
19.1.2025 11:59:00

Similar issue for German server (minus the time-related issue):

<img width="139" alt="Image" src="https://github.com/user-attachments/assets/2682bbfb-92e0-4110-90b2-7bf19083a280" />

16.1.2025 02:17:00
19.1.2025 23:20:00

**Comment by Beelzebob6666** [comment]
thanks - fixed in beta

**Comment by kleopatra** [comment]
date looks okay now, thanks! 

Time part (am/pm -> 24hr format conversion) is still wrong (beta server, probably all locales with am/pm). Do you want a new issue or details here?

**Comment by Beelzebob6666** [comment]
fixed thanks!

**Comment by kleopatra** [comment]
thanks for your efforts (and apologies for not coming back earler, life happens ;)

Unfortunately, we seem to be back (or near) at the start: date jumps between last pseudo and first real date, all before are incorrect. All examples are from beta server .

Shot from in-game list (exported today, 26. Feb):

<img width="140" alt="Image" src="https://github.com/user-attachments/assets/155b22e5-35aa-44ff-a426-fdc6b93b272b" />

exported as:

20.2.2025 12:01:00
23.2.2025 10:58:00

also note the incorrect time part: the local of the export looks like German (or at least a 24h time format), so the time should be 0:01:00

looks like the times are somehow shifted by 12h

example first entry in-game log:

<img width="104" alt="Image" src="https://github.com/user-attachments/assets/c1feb2a6-b0bc-49b2-ad86-e66c942c5807" />

exported as:

26.2.2025 02:50:00

expected:

26.2.2025 14:50:00

**Comment by Beelzebob6666** [comment]
Are you using bet branch of the extension?
Pretty sure there was no official release since I implemented the last fix

**Comment by kleopatra** [comment]
no beta helper, just beta foe server. Don't know when you changed it relative to me looking closely the last time ;) Only seeing that now it's back to stage 1: both date and time part are incorrect (while intermediately the date part was correct)

**Comment by kleopatra** [comment]
looks okay now, both date and time conversion - version 3.11.0.0. Thanks!
